#pragma once

#define EGErrorCode_OPERATION_DENIED             (   -3)
#define EGErrorCode_OPERATION_INVALID            (   -2)
#define EGErrorCode_INTERNAL_SERVER_ERROR        (   -1)
#define EGErrorCode_OK                           (    0)
#define EGErrorCode_INVALID_AUTHENTICATION       (32767)
#define EGErrorCode_GAME_ID_ALREADY_EXISTS       (32766)
#define EGErrorCode_GAME_FULL                    (32765)
#define EGErrorCode_GAME_CLOSED                  (32764)
#define EGErrorCode_ALREADY_MATCHED              (32763)
#define EGErrorCode_SERVER_FULL                  (32762)
#define EGErrorCode_USER_BLOCKED                 (32761)
#define EGErrorCode_NO_MATCH_FOUND               (32760)
#define EGErrorCode_GAME_DOES_NOT_EXIST          (32758)
#define EGErrorCode_MAX_CCU_REACHED              (32757)
#define EGErrorCode_INVALID_REGION               (32756)
#define EGErrorCode_CUSTOM_AUTHENTICATION_FAILED (32755)