#pragma once

#define EGPeerStates_Uninitialized                              ( 0)
#define EGPeerStates_PeerCreated                                ( 1)
#define EGPeerStates_ConnectingToNameserver                     ( 2)
#define EGPeerStates_ConnectedToNameserver                      ( 3)
#define EGPeerStates_DisconnectingFromNameserver                ( 4)
#define EGPeerStates_Connecting                                 ( 5)
#define EGPeerStates_Connected                                  ( 6)
#define EGPeerStates_WaitingForCustomAuthenticationNextStepCall ( 7)
#define EGPeerStates_Authenticated                              ( 8)
#define EGPeerStates_JoinedLobby                                ( 9)
#define EGPeerStates_DisconnectingFromMasterserver              (10)
#define EGPeerStates_ConnectingToGameserver                     (11)
#define EGPeerStates_ConnectedToGameserver                      (12)
#define EGPeerStates_AuthenticatedOnGameServer                  (13)
#define EGPeerStates_Joining                                    (14)
#define EGPeerStates_Joined                                     (15)
#define EGPeerStates_Leaving                                    (16)
#define EGPeerStates_Left                                       (17)
#define EGPeerStates_DisconnectingFromGameserver                (18)
#define EGPeerStates_ConnectingToMasterserver                   (19)
#define EGPeerStates_ConnectedComingFromGameserver              (20)
#define EGPeerStates_AuthenticatedComingFromGameserver          (21)
#define EGPeerStates_Disconnecting                              (22)
#define EGPeerStates_Disconnected                               (23)